### ISSUE TITLE
core_api sometimes fails due to a warning about session_start()

### ISSUE THREAD

**Issue by benbrown** [xoxco/PeoplePods#5]
In some (unknown) circumstances, core_api will print out an error about sesson_start() before printing out the JSON results, thus causing the API call to fail on the javascript side.

The API call succeeds, but the return value to the Javascript client is invalid due to the warning.  This makes it appear as if the API call failed, when in reality it succeeded.

**Comment by paularmand** [comment]
@Ben, maybe it's not the cause of this warning, but it might just be: Looking at the source code of the core_simple_api pod, the first character of both index_version.php files is a space, " <?". This should be "<?" hence without the space, since the output will start because this space is send back. It's just a remark, and probably unrelated to this issue since one would expect a 'headers already sent" warning from this, in contrast to your issue description which states a "session_start()" warning, but hey the space should go anyway ;)

**Comment by benbrown** [comment]
True!  I will fix that.

**Comment by benbrown** [comment]
OK!  Leading spaces have been removed.

**Comment by paularmand** [comment]
If this error persists, could you please copy and paste it here? 
Note to @self: "Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent" means better check encoding of file (utf-8 versus ?)

**Comment by benbrown** [comment]
I think that this error WAS in fact due to the leading space in the API files.  DOH!  I need @mrahfa to update his code in order to check.

**Comment by paularmand** [comment]
@mrahfa A subtle and gentle reminder that is ;)

**Comment by benbrown** [comment]
Subtle and gentle is my middle name.

Just saw your oauth pod!  Very exciting.

**Comment by paularmand** [comment]
Thanks, I hope it's useful.

**Comment by benbrown** [comment]
It is "done" enough that I should evaluate it now?

**Comment by paularmand** [comment]
Yep, I believe it's "done" enough. But I don't known your/xoxco's coding style/practices/requirements, so now you got me scared of pull requesting anything else ;)

**Comment by benbrown** [comment]
Nono, don't be scared!  Send those pull requests! I love them, it is super exciting to receive them.  I just need time to review everything before I roll it in to the main branch.

**Comment by paularmand** [comment]
:)

**Comment by mrahfa** [comment]
@benbrown, @paularmand now subdomain installation is working. Do I need to update my themes?

**Comment by benbrown** [comment]
Nope! Themes should be unaffected!
